name: dbt_biathlon
version: '1.0.0'
profile: dbt_biathlon

model-paths: ["models"]
seed-paths: []
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  dbt_biathlon:
    +materialized: view
    +persist_docs:
      relation: true
      columns: true
